version: '3.8'
services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d
    environment:
      - NODE_ENV=prod